{
    'name': 'AI Concierge - Supply Chain Bridge',
    'version': '19.0.1.0.0',
    'category': 'Inventory/Inventory',
    'summary': 'Glue module between AI Concierge and Supply Forecast for intelligent replenishment insights',
    'author': 'TMFCoders SL',
    'website': 'https://tmfcoders.com',
    'price': 29.00,
    'currency': 'EUR',
    'license': 'OPL-1',
    'depends': ['ai_concierge', 'supply_forecast'],
    'data': [],
    'installable': True,
    'auto_install': True,
}
